### PR TITLE
Update the online derivation validation behavior

### PR DESCRIPTION
**Pull request by yuli-han**
## Summary

We used to exclude the keys columns for online joins/group_bys because keys are not included in the online fetching result. But there are some use cases where the user firstly add keys in offline group_bys derivations, then mark the offline group_by to be online. The validator failed in this case because we are not allowed online derivation on keys. We don't want users to change their offline derivation behavior just to pass the validator and recompute everything. 

This PR is to update the validator behavior to enable online derivations on keys. Although online derivation on keys are not gonna make any difference in fetching result, it won't break the re-compiling on existing offline entity. 

## Test Plan

- [x] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested

## Checklist
- [ ] Documentation update

## Reviewers
@hzding621 @donghanz

### CODE REVIEW

**Comment by hzding621** [comment]
@yuli-han it seems we do allow online derivations on keys after all? https://github.com/airbnb/chronon/blob/main/online/src/main/scala/ai/chronon/online/OnlineDerivationUtil.scala#L43

otherwise, user's gb in the scenario you described would fail online, right?

**Comment by yuli-han** [comment]
@hzding621 Yep! By disable I mean currently the compiler will fail if users change their offline group_by with derivation on keys to online. But the online derivation on keys is always supported from the fetcher side. So I make this change to enable this in compiler as well.

**Comment by yuli-han** [comment]
Confirmed that online derivation supports derivation on keys

**Comment by pkundurthy** [comment]
Do we need to update any documentation to remove any previous notes on validation failing on offline -> online change? @yuli-han 
LGTM: stamped.

**Review by pkundurthy — APPROVED** [review]

**Pull request merged**
